[package]
name = "tsc_compile_build"
version = "0.12.0-dev.0"
authors = ["ChiselStrike"]
edition = "2021"

[lib]
name = "tsc_compile_build"

[dependencies]
bundle-deepkit-type-compile = { path = "../bundle-deepkit-type-compile" }
