[package]
name = "endpoint_tsc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tsc_compile = { path = "../tsc_compile" }
anyhow = "1.0"
api = { path = "../api" }
url = "2.2"

[lib]
name = "endpoint_tsc"
