[package]
name = "my_tsc"
version = "0.10.0-dev.0"
authors = ["ChiselStrike"]
edition = "2021"

[dependencies]
deno_runtime = { path = "../third_party/deno/runtime" }
structopt = "0.3.23"
tokio = "1.11.0"
tsc_compile = { path = "../tsc_compile" }

[[bin]]
name = "my_tsc"
path = "src/main.rs"
