const path = require("path");

module.exports = {
    experiments: { outputModule: true }, /* required so webpack emits modules */
    /* the entry point will be auto-generated by ChiselStrike and it is then empty */
    output: {
        filename: "endpoint.mjs",
        chunkFormat: "module",
        library: {
            type: "module",
        },
    },
    optimization: {
        minimize: false,
    },
    externalsPresets: {
        web: true, /* handle https://... as external modules */
    },
    mode: "production",
    module: {
        rules: [
            {
                test: /\.ts$/,
                exclude: /node_modules/,
                use: [{
                    loader: "ts-loader",
                    options: {
                        /* otherwise it will try to find it on the tmpdir where we wrote the entry point */
                        configFile: path.resolve(
                            process.cwd(),
                            "tsconfig.json",
                        ),
                    },
                }],
            },
        ],
    },
    target:
        "es2020", /* or node13 or later, otherwise it won't understand import/export statements */
    resolve: {
        extensions: [".tsx", ".ts", ".js"],
    },
};
