#!/bin/bash

# FIXME: Use default job-level parallelism when the "bad archive" problem discussed in https://github.com/chiselstrike/chiselstrike/issues/777 is resolved.

cargo install -j1 --path server --bin chiseld
cargo install -j1 --path cli --bin chisel
